-- Verifica que no exista la tabla
DECLARE
    tabla VARCHAR2(15) := 'TBL_CANTON';
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ' || tabla;
  DBMS_OUTPUT.PUT_LINE('LA TABLA ' || tabla || ' FUE ENCONTRADA Y ELIMINADA EXITOSAMENTE');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('LA TABLA ' || tabla || ' NO EXISTE');
END;
/

--Crear tabla
CREATE TABLE TBL_CANTON(
    ID_CANTON NUMBER NOT NULL PRIMARY KEY,
    NOMBRE_CANTON VARCHAR2(50) NOT NULL,
    ID_PROVINCIA NUMBER,
    CONSTRAINT FK_CANTON_PROVINCIA
    FOREIGN KEY (ID_PROVINCIA)
    REFERENCES TBL_PROVINCIA(ID_PROVINCIA)
);

-- SP para insertar datos en tabla TBL_CANTON
CREATE OR REPLACE PROCEDURE SP_INSERTAR_CANTON (
    P_ID_CANTON TBL_CANTON.ID_CANTON%TYPE,
    P_NOMBRE_CANTON TBL_CANTON.NOMBRE_CANTON%TYPE,
    P_ID_PROVINCIA TBL_CANTON.ID_PROVINCIA%TYPE
) AS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM TBL_CANTON
    WHERE ID_CANTON = P_ID_CANTON;

    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON EL ID ' || P_ID_CANTON);
    ELSE
        INSERT INTO TBL_CANTON (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA)
        VALUES (P_ID_CANTON, P_NOMBRE_CANTON, P_ID_PROVINCIA);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('REGISTRO REALIZADO');
    END IF;
END;
/

-- SP para actualizar datos en tabla TBL_CANTON
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_CANTON (
    P_ID_CANTON IN TBL_CANTON.ID_CANTON%TYPE,
    P_NUEVO_NOMBRE_CANTON IN TBL_CANTON.NOMBRE_CANTON%TYPE
) IS
BEGIN
    UPDATE TBL_CANTON
    SET NOMBRE_CANTON = P_NUEVO_NOMBRE_CANTON
    WHERE ID_CANTON = P_ID_CANTON;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Registro actualizado exitosamente');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró un registro con el ID ' || P_ID_CANTON);
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al procesar la operación');
END SP_ACTUALIZAR_CANTON;
/

-- SP para eliminar datos en tabla TBL_CANTON
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_CANTON (
    P_ID_CANTON IN TBL_CANTON.ID_CANTON%TYPE
) IS
BEGIN
    DELETE FROM TBL_CANTON
    WHERE ID_CANTON = P_ID_CANTON;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Registro eliminado exitosamente');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró un registro con el ID ' || P_ID_CANTON);
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al procesar la operación');
END SP_ELIMINAR_CANTON;
/

-- SP para leer datos en tabla TBL_CANTON
CREATE OR REPLACE PROCEDURE SP_LEER_CANTON(
    P_ID_CANTON NUMBER
)IS
    V_ID_CANTON TBL_CANTON.ID_CANTON%TYPE;
    V_NOMBRE_CANTON TBL_CANTON.NOMBRE_CANTON%TYPE;
BEGIN    
    SELECT ID_CANTON, NOMBRE_CANTON INTO V_ID_CANTON, V_NOMBRE_CANTON
    FROM TBL_CANTON
    WHERE ID_CANTON = P_ID_CANTON;
    
    DBMS_OUTPUT.PUT_LINE('ID DEL CANTON: ' || V_ID_CANTON || ', EL NOMBRE DEL CANTON ES: ' || V_NOMBRE_CANTON);
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('EL CANTON CON EL ID ' || P_ID_CANTON || ' NO FUE ENCONTRADO.');
END;
/

--Inicia bloque funciones
--Consulta la provincia a la que corresponde un canton
CREATE OR REPLACE FUNCTION CONSULTAR_CANTON(NOMBRE_CANTON_IN VARCHAR2)
RETURN VARCHAR2
IS
    NOMBRE_CANTON TBL_CANTON.NOMBRE_CANTON%TYPE;
    NOMBRE_PROVINCIA TBL_PROVINCIA.NOMBRE_PROVINCIA%TYPE;
BEGIN
    -- Buscar el nombre del canton en la tabla TBL_CANTON
    SELECT C.NOMBRE_CANTON, P.NOMBRE_PROVINCIA
    INTO NOMBRE_CANTON, NOMBRE_PROVINCIA
    FROM TBL_CANTON C
    INNER JOIN TBL_PROVINCIA P ON C.ID_PROVINCIA = P.ID_PROVINCIA
    WHERE REGEXP_LIKE (C.NOMBRE_CANTON,NOMBRE_CANTON_IN,'i');

    -- Retornar el resultado
    RETURN 'EL CANTON CON NOMBRE: ' || NOMBRE_CANTON || ' PERTENECE A LA PROVINCIA ' || NOMBRE_PROVINCIA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'CANTON' || NOMBRE_CANTON || ' NO ENCONTRADO';
    WHEN OTHERS THEN
        RETURN 'ERROR AL CONSULTAR EL CANTON';
END;
/

--Busqueda de canton por id
CREATE OR REPLACE FUNCTION CONSULTAR_CANTON_CON_ID(ID_CANTON_IN NUMBER)
RETURN VARCHAR2
IS
    ID_CANTON TBL_CANTON.ID_CANTON%TYPE;
    NOMBRE_CANTON TBL_CANTON.NOMBRE_CANTON%TYPE;
BEGIN
    -- Buscar el ID del canton en la tabla TBL_CANTON
    SELECT C.ID_CANTON, C.NOMBRE_CANTON
    INTO ID_CANTON, NOMBRE_CANTON
    FROM TBL_CANTON C
    WHERE ID_CANTON = ID_CANTON_IN;

    -- Retornar el resultado
    RETURN 'EL CANTON CON ID: ' || ID_CANTON || ' SE LLAMA: ' || NOMBRE_CANTON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'EL CANTON CON ID: ' || ID_CANTON || ' NO FUE ENCONTRADO';
    WHEN OTHERS THEN
        RETURN 'ERROR AL CONSULTAR EL CANTON';
END;
/

--VISTA PARA LISTAR TODOS LOS CANTONES
CREATE OR REPLACE VIEW VISTA_LISTAR_CANTONES AS 
SELECT C.ID_CANTON "NUMERO DE CANTON", Upper(C.NOMBRE_CANTON) "NOMBRE DEL CANTON", Upper(P.NOMBRE_PROVINCIA) "PERTENECE A LA PROVINCIA DE" FROM TBL_CANTON C
INNER JOIN TBL_PROVINCIA P ON C.ID_PROVINCIA = P.ID_PROVINCIA
ORDER BY P.ID_PROVINCIA;

--VISTA PARA VER LA CANTIDAD DE CANTONES EN EL PAÍS
CREATE OR REPLACE VIEW VISTA_CANTIDAD_DE_CANTONES AS 
SELECT COUNT(ID_CANTON) "NUMERO DE CANTONES" FROM TBL_CANTON WITH READ ONLY;

--CURSOR PARA LISTAR LOS CANTONES QUE EMPIECEN CON UNA LETRA EN ESPECIFICO
DECLARE
    CURSOR c_cantones IS
        SELECT C.ID_CANTON, C.NOMBRE_CANTON, P.NOMBRE_PROVINCIA
        FROM TBL_CANTON C
        INNER JOIN TBL_PROVINCIA P ON C.ID_PROVINCIA = P.ID_PROVINCIA
        WHERE REGEXP_LIKE(C.NOMBRE_CANTON, '^A')
        ORDER BY P.NOMBRE_PROVINCIA, C.NOMBRE_CANTON;

    v_id_canton TBL_CANTON.ID_CANTON%TYPE;
    v_nombre_canton TBL_CANTON.NOMBRE_CANTON%TYPE;
    v_nombre_provincia TBL_PROVINCIA.NOMBRE_PROVINCIA%TYPE;
BEGIN
    OPEN c_cantones;
    LOOP
        FETCH c_cantones INTO v_id_canton, v_nombre_canton, v_nombre_provincia;
        EXIT WHEN c_cantones%NOTFOUND;

        dbms_output.put_line('Provincia: ' || v_nombre_provincia || ' -- Nombre del Cantón: ' || v_nombre_canton);
    END LOOP;
    CLOSE c_cantones;
END;
/

--CURSOR PARA LISTAR LOS CANTONES EN UN RANGO DE ID
DECLARE
    CURSOR C_CANTONES IS
        SELECT ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA
        FROM TBL_CANTON
        WHERE ID_CANTON BETWEEN 100 AND 110
        ORDER BY ID_CANTON;

    v_id_canton TBL_CANTON.ID_CANTON%TYPE;
    v_nombre_canton TBL_CANTON.NOMBRE_CANTON%TYPE;
    v_id_provincia TBL_CANTON.ID_PROVINCIA%TYPE;
BEGIN
    OPEN C_CANTONES;

    LOOP
        FETCH C_CANTONES INTO v_id_canton, v_nombre_canton, v_id_provincia;
        EXIT WHEN C_CANTONES%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('ID CANTON: ' || v_id_canton || ', NOMBRE DEL CANTON: ' || v_nombre_canton || ', ID PROVINCIA: ' || v_id_provincia);
    END LOOP;

    CLOSE C_CANTONES;
END;
/

-- Insercion de cantones
--San Jose
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES (101,1,'San José');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES (102,1,'Escazú');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (103,1,'Desamparados');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (104,1,'Puriscal');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (105,1,'Tarrazú');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (106,1,'Aserrí');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (107,1,'Mora');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (108,1,'Goicoechea');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (109,1,'Santa Ana');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (110,1,'Alajuelita');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (111,1,'Vasquez de Coronado');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (112,1,'Acosta');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (113,1,'Tibás');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (114,1,'Moravia');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (115,1,'Montes de Oca');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (116,1,'Turrubares');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (117,1,'Dota');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (118,1,'Curridabat');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (119,1,'Pérez Zeledón');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (120,1,'León Cortés');

--Alajuela
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (201,2,'Alajuela');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (202,2,'San Ramón');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (203,2,'Grecia');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (204,2,'San Mateo');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (205,2,'Atenas');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (206,2,'Naranjo');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (207,2,'Palmares');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (208,2,'Poás');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (209,2,'Orotina');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (210,2,'San Carlos');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (211,2,'Zarcero');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (212,2,'Sarchí');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (213,2,'Upala');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (214,2,'Los Chiles');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (215,2,'Guatuso');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (216,2,'Río Cuarto');

--Cartago
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (301,3,'Cartago');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (302,3,'Paraíso');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (303,3,'La Unión');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (304,3,'Jiménez');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (305,3,'Turrialba');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (306,3,'Alvarado');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (307,3,'Oreamuno');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (308,3,'El Guarco');

--Heredia
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (401,4,'Heredia');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (402,4,'Barva');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (403,4,'Santo Domingo');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (404,4,'Santa Bárbara');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (405,4,'San Rafael');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (406,4,'San Isidro');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (407,4,'Belén');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (408,4,'Flores');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (409,4,'San Pablo');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (410,4,'Sarapiquí');

--Guanacaste
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (501,5,'Liberia');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (502,5,'Nicoya');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (503,5,'Santa Cruz');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (504,5,'Bagaces');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (505,5,'Carrillo');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (506,5,'Cañas');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (507,5,'Abangares');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (508,5,'Tilarán');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (509,5,'Nandayure');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (510,5,'La Cruz');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (511,5,'Hojancha');

--Puntarenas
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (601,6,'Puntarenas');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (602,6,'Esparza');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (603,6,'Buenos Aires');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (604,6,'Montes de Oro');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (605,6,'Osa');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (606,6,'Aguirre');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (607,6,'Golfito');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (608,6,'Coto Brus');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (609,6,'Parrita');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (610,6,'Corredores');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (611,6,'Garabito');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (612,6,'Monteverde');

--Limon
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (701,7,'Limón');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (702,7,'Pococí');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (703,7,'Siquirres ');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (704,7,'Talamanca');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (705,7,'Matina');
INSERT INTO TBL_CANTON (ID_CANTON,ID_PROVINCIA,NOMBRE_CANTON) VALUES  (706,7,'Guácimo');

-- Bloque CRUD con SPs para TBL_CANTON
//EXEC sp_insertar_canton(101,'San José',1);
//EXEC sp_actualizar_canton(101,'Cartago');
//EXEC sp_eliminar_canton(101);
//EXEC sp_leer_canton(101);

--Llamando la vista Canton
SELECT "NUMERO DE CANTON", "NOMBRE DEL CANTON", "PERTENECE A LA PROVINCIA DE" FROM VISTA_LISTAR_CANTONES;
SELECT "NUMERO DE CANTONES" FROM VISTA_CANTIDAD_DE_CANTONES;

--Llamando funciones de Canton
SELECT CONSULTAR_CANTON('MorAvIa') FROM DUAL;
SELECT CONSULTAR_CANTON('SaN rAfAEl') FROM DUAL;
SELECT CONSULTAR_CANTON_CON_ID(103) FROM DUAL;
