-- Verifica que no exista la tabla
DECLARE
    tabla VARCHAR2(15) := 'TBL_DISTRITO';
    tabla2 VARCHAR2(60) := 'TABLA_RESULTADOS';
    tabla3 VARCHAR2(50) := 'TIPO_RESULTADO';
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ' || tabla;
  EXECUTE IMMEDIATE 'DROP TYPE ' || tabla2;
  EXECUTE IMMEDIATE 'DROP TYPE ' || tabla3;
  DBMS_OUTPUT.PUT_LINE('LA TABLA ' || tabla || ' FUE ENCONTRADA Y ELIMINADA EXITOSAMENTE');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('LA TABLA ' || tabla || ' NO EXISTE');
END;
/

--Crear tabla
CREATE TABLE TBL_DISTRITO(
    ID_DISTRITO NUMBER NOT NULL PRIMARY KEY,
    NOMBRE_DISTRITO VARCHAR2(50) NOT NULL,
    ID_CANTON NUMBER,
    CONSTRAINT FK_DISTRITO_CANTON
    FOREIGN KEY (ID_CANTON)
    REFERENCES TBL_CANTON(ID_CANTON)
);

CREATE OR REPLACE PACKAGE pkg_distrito_utilidades AS
    -- Declaración de los procedimientos
    PROCEDURE sp_insertar_distrito(
        p_id_distrito TBL_DISTRITO.ID_DISTRITO%TYPE,
        p_nombre_distrito TBL_DISTRITO.NOMBRE_DISTRITO%TYPE,
        p_id_canton TBL_DISTRITO.ID_CANTON%TYPE
    );

    PROCEDURE sp_actualizar_distrito(
        p_id_distrito IN TBL_DISTRITO.ID_DISTRITO%TYPE,
        p_nuevo_nombre_distrito IN TBL_DISTRITO.NOMBRE_DISTRITO%TYPE
    );

    PROCEDURE sp_eliminar_distrito(
        p_id_distrito IN TBL_DISTRITO.ID_DISTRITO%TYPE
    );

    PROCEDURE sp_leer_distrito(
        p_id_distrito NUMBER
    );
END pkg_distrito_utilidades;
/

-- Cuerpo del Paquete
CREATE OR REPLACE PACKAGE BODY pkg_distrito_utilidades AS

    -- Implementación del procedimiento para insertar distritos
    PROCEDURE sp_insertar_distrito (
        p_id_distrito TBL_DISTRITO.ID_DISTRITO%TYPE,
        p_nombre_distrito TBL_DISTRITO.NOMBRE_DISTRITO%TYPE,
        p_id_canton TBL_DISTRITO.ID_CANTON%TYPE
    ) AS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM TBL_DISTRITO
        WHERE ID_DISTRITO = p_id_distrito;

        IF v_count > 0 THEN
            DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON EL ID ' || p_id_canton);
        ELSE
            INSERT INTO TBL_DISTRITO (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON)
            VALUES (p_id_distrito, p_nombre_distrito, p_id_canton);
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('REGISTRO REALIZADO');
        END IF;
    END sp_insertar_distrito;

    -- Implementación del procedimiento para actualizar distritos
    PROCEDURE sp_actualizar_distrito (
        p_id_distrito IN TBL_DISTRITO.ID_DISTRITO%TYPE,
        p_nuevo_nombre_distrito IN TBL_DISTRITO.NOMBRE_DISTRITO%TYPE
    ) IS
    BEGIN
        UPDATE TBL_DISTRITO
        SET NOMBRE_DISTRITO = p_nuevo_nombre_distrito
        WHERE ID_DISTRITO = p_id_distrito;

        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Registro actualizado exitosamente');
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('No se encontró un registro con el ID ' || p_id_distrito);
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error al procesar la operación');
    END sp_actualizar_distrito;

    -- Implementación del procedimiento para eliminar distritos
    PROCEDURE sp_eliminar_distrito (
        p_id_distrito IN TBL_DISTRITO.ID_DISTRITO%TYPE
    ) IS
    BEGIN
        DELETE FROM TBL_DISTRITO
        WHERE ID_DISTRITO = p_id_distrito;

        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Registro eliminado exitosamente');
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('No se encontró un registro con el ID ' || p_id_distrito);
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error al procesar la operación');
    END sp_eliminar_distrito;

    -- Implementación del procedimiento para leer distritos
    PROCEDURE sp_leer_distrito(
        p_id_distrito NUMBER
    ) IS
        v_id_distrito TBL_DISTRITO.ID_DISTRITO%TYPE;
        v_nombre_distrito TBL_DISTRITO.NOMBRE_DISTRITO%TYPE;
    BEGIN    
        SELECT ID_DISTRITO, NOMBRE_DISTRITO INTO v_id_distrito, v_nombre_distrito
        FROM TBL_DISTRITO
        WHERE ID_DISTRITO = p_id_distrito;
        
        DBMS_OUTPUT.PUT_LINE('ID DEL DISTRITO: ' || v_id_distrito || ', EL NOMBRE DEL DISTRITO ES: ' || v_nombre_distrito);
        
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('EL DISTRITO CON EL ID ' || p_id_distrito || ' NO FUE ENCONTRADO.');
    END sp_leer_distrito;

END pkg_distrito_utilidades;
/


--CURSOR PARA LISTAR LOS DISTRITOS EN UN RANGO SEGUN SU ID
DECLARE
    CURSOR C_DISTRITOS IS
        SELECT ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON
        FROM TBL_DISTRITO
        WHERE ID_DISTRITO BETWEEN 30101 AND 30205
        ORDER BY ID_DISTRITO;

    v_id_distrito TBL_DISTRITO.ID_DISTRITO%TYPE;
    v_nombre_distrito TBL_DISTRITO.NOMBRE_DISTRITO%TYPE;
    v_id_canton TBL_DISTRITO.ID_CANTON%TYPE;
BEGIN
    OPEN C_DISTRITOS;

    LOOP
        FETCH C_DISTRITOS INTO v_id_distrito, v_nombre_distrito, v_id_canton;
        EXIT WHEN C_DISTRITOS%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('ID DISTRITO: ' || v_id_distrito || ', NOMBRE DEL DISTRITO: ' || v_nombre_distrito || ', ID CANTON: ' || v_id_canton);
    END LOOP;

    CLOSE C_DISTRITOS;
END;
/

--Inicia bloque funciones

-- **Inicia bloque de codigo para manejo de multiples resultados devueltos por una funcion**

-- Crear el tipo de objeto que retornara la funcion en este caso devolvera dos columnas 'nombre_distrito' y 'nombre_canton'
CREATE OR REPLACE TYPE TIPO_RESULTADO AS OBJECT (
    NOMBRE_DISTRITO VARCHAR2(50),
    NOMBRE_CANTON VARCHAR2(50)
);
/

-- Crear el tipo de tabla, esto nos permitirá manejar multiples resultados en la función
CREATE OR REPLACE TYPE TABLA_RESULTADOS AS TABLE OF TIPO_RESULTADO;
/

CREATE OR REPLACE PACKAGE pkg_distrito AS
    TYPE tipo_resultado IS RECORD (
        nombre_distrito VARCHAR2(100),
        nombre_canton VARCHAR2(100)
    );
    
    TYPE tabla_resultados IS TABLE OF tipo_resultado;

    FUNCTION consultar_distrito_por_nombre(
        nombre_distrito_in VARCHAR2
    ) RETURN tabla_resultados PIPELINED;

    FUNCTION consultar_distrito_con_id(
        id_distrito_in NUMBER
    ) RETURN VARCHAR2;
END pkg_distrito;
/

CREATE OR REPLACE PACKAGE BODY pkg_distrito AS

    FUNCTION consultar_distrito_por_nombre(
        nombre_distrito_in VARCHAR2
    ) RETURN tabla_resultados PIPELINED
    IS
        v_found BOOLEAN := FALSE;
    BEGIN
        FOR R IN (
            SELECT D.NOMBRE_DISTRITO, C.NOMBRE_CANTON
            FROM TBL_DISTRITO D 
            INNER JOIN TBL_CANTON C ON D.ID_CANTON = C.ID_CANTON
            WHERE REGEXP_LIKE(D.NOMBRE_DISTRITO, nombre_distrito_in, 'i')
        ) LOOP
            PIPE ROW(tipo_resultado(R.NOMBRE_DISTRITO, R.NOMBRE_CANTON));
            v_found := TRUE;
        END LOOP;

        IF NOT v_found THEN
            PIPE ROW(tipo_resultado('DISTRITO NO ENCONTRADO', 'NO SE PUEDE BUSCAR CANTON SIN DISTRITO'));
        END IF;

        RETURN;
    EXCEPTION
        WHEN OTHERS THEN
            PIPE ROW(tipo_resultado('ERROR AL CONSULTAR EL DISTRITO', 'ERROR AL CONSULTAR EL CANTON'));
            RETURN;
    END;

    FUNCTION consultar_distrito_con_id(
        id_distrito_in NUMBER
    ) RETURN VARCHAR2
    IS
        id_distrito TBL_DISTRITO.ID_DISTRITO%TYPE;
        nombre_distrito TBL_DISTRITO.NOMBRE_DISTRITO%TYPE;
    BEGIN
        -- Buscar el nombre del distrito en la tabla TBL_DISTRITO
        SELECT D.ID_DISTRITO, D.NOMBRE_DISTRITO
        INTO id_distrito, nombre_distrito
        FROM TBL_DISTRITO D
        WHERE D.ID_DISTRITO = id_distrito_in;

        -- Retornar el resultado
        RETURN 'EL DISTRITO CON ID: ' || id_distrito || ' SE LLAMA: ' || nombre_distrito;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 'EL DISTRITO CON ID: ' || id_distrito_in || ' NO FUE ENCONTRADO';
        WHEN OTHERS THEN
            RETURN 'ERROR AL CONSULTAR EL DISTRITO';
    END;

END pkg_distrito;
/


--VISTA PARA LISTAR TODOS LOS DISTRITO Y SUS RESPECTIVOS CANTONES
CREATE OR REPLACE VIEW VISTA_LISTAR_DISTRITO AS 
SELECT Upper(D.NOMBRE_DISTRITO) "NOMBRE DEL DISTRITO", C.ID_CANTON "NUMERO DE CANTON", Upper(C.NOMBRE_CANTON) "NOMBRE DEL CANTON" FROM TBL_DISTRITO D
INNER JOIN TBL_CANTON C ON D.ID_CANTON = C.ID_CANTON
ORDER BY D.ID_DISTRITO;

--VISTA PARA LISTAR TODOS LOS DISTRITO Y SUS RESPECTIVOS CANTONES Y PROVINCIAS
CREATE OR REPLACE VIEW VISTA_LISTAR_DISTRITO_Y_PROVINCIA AS 
SELECT D.NOMBRE_DISTRITO "NOMBRE DEL DISTRITO", C.ID_CANTON "NUMERO DE CANTON", Upper(C.NOMBRE_CANTON) "NOMBRE DEL CANTON", Upper(P.NOMBRE_PROVINCIA) "PERTENECE A LA PROVINCIA DE" FROM TBL_CANTON C
INNER JOIN TBL_PROVINCIA P ON C.ID_PROVINCIA = P.ID_PROVINCIA
INNER JOIN TBL_DISTRITO D ON D.ID_CANTON = C.ID_CANTON
ORDER BY D.ID_DISTRITO;

--VISTA PARA VER LA CANTIDAD DE DISTRITOS EN EL PAÍS
CREATE OR REPLACE VIEW VISTA_CANTIDAD_DE_DISTRITOS AS 
SELECT COUNT(ID_DISTRITO) "NUMERO DE DISTRITOS" FROM TBL_DISTRITO WITH READ ONLY;

--Insercion de distritos
INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10101, 'Carmen');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10102, 'Merced');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10103, 'Hospital');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10104, 'Catedral');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10105, 'Zapote');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10106, 'San Francisco de Dos Ríos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10107, 'Uruca');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10108, 'Mata Redonda');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10109, 'Pavas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10110, 'Hatillo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (101, 10111, 'San Sebastián');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (102, 10201, 'Escazú');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (102, 10202, 'San Antonio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (102, 10203, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10301, 'Desamparados');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10302, 'San Miguel');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10303, 'San Juan de Dios');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10304, 'San Rafael Arriba');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10305, 'San Antonio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10306, 'Frailes');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10307, 'Patarra');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10308, 'San Cristobal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10309, 'Rosario');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10310, 'Damas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10311, 'San Rafael Abajo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10312, 'Gravilias');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (103, 10313, 'Los Guido');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10401, 'Santiago');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10402, 'Mercedes Sur');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10403, 'Barbacoas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10404, 'Grifo Alto');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10405, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10406, 'Candelarita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10407, 'Desamparaditos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10408, 'San Antonio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (104, 10409, 'Chires');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (105, 10501, 'San Marcos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (105, 10502, 'San Lorenzo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (105, 10503, 'San Carlos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (106, 10601, 'Aserrí');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (106, 10602, 'Tarbaca');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (106, 10603, 'Vuelta de Jorco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (106, 10604, 'San Gabriel');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (106, 10605, 'Legua');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (106, 10606, 'Monterrey');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (106, 10607, 'Salitrillos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (107, 10701, 'Colón');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (107, 10702, 'Guayabo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (107, 10703, 'Tabarcia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (107, 10704, 'Piedras Negras');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (107, 10705, 'Picagres');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (107, 10706, 'Jaris');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (107, 10707, 'Quitirrisí');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (108, 10801, 'Guadalupe');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (108, 10802, 'San Francisco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (108, 10803, 'Calle Blancos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (108, 10804, 'Mata de Plátano');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (108, 10805, 'Ipis');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (108, 10806, 'Rancho Redondo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (108, 10807, 'Purral');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (109, 10901, 'Santa Ana');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (109, 10902, 'Salitral');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (109, 10903, 'Pozos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (109, 10904, 'Uruca');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (109, 10905, 'Piedades');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (109, 10906, 'Brasil');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (110, 11001, 'Alajuelita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (110, 11002, 'San Josecito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (110, 11003, 'San Antonio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (110, 11004, 'Concepción');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (110, 11005, 'San Felipe');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (111, 11101, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (111, 11102, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (111, 11103, 'Dulce Nombre de Jesús');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (111, 11104, 'Patalillo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (111, 11105, 'Cascajal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (112, 11201, 'San Ignacio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (112, 11202, 'Guaitil');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (112, 11203, 'Palmichal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (112, 11204, 'Cangrejal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (112, 11205, 'Sabanillas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (113, 11301, 'San Juan');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (113, 11302, 'Cinco Esquinas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (113, 11303, 'Anselmo Llorente');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (113, 11304, 'León XIII');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (113, 11305, 'Colima');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (114, 11401, 'San Vicente');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (114, 11402, 'San Jerónimo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (114, 11403, 'La Trinidad');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (115, 11501, 'San Pedro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (115, 11502, 'Sabanilla');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (115, 11503, 'Mercedes');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (115, 11504, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (116, 11601, 'San Pablo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (116, 11602, 'San Pedro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (116, 11603, 'San Juan de Mata');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (116, 11604, 'San Luis');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (116, 11605, 'Carara');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (117, 11701, 'Santa María');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (117, 11702, 'Jardín');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (117, 11703, 'Copey');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (118, 11801, 'Curridabat');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (118, 11802, 'Granadilla');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (118, 11803, 'Sánchez');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (118, 11804, 'Tirrases');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11901, 'San Isidro de El General');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11902, 'El General');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11903, 'Daniel Flores');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11904, 'Rivas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11905, 'San Pedro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11906, 'Platanares');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11907, 'Pejibaye');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11908, 'Cajón');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11909, 'Barú');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11910, 'Río Nuevo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11911, 'Paramo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (119, 11912, 'La  Amistad');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (120, 12001, 'San Pablo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (120, 12002, 'San Andrés');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (120, 12003, 'Llano Bonito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (120, 12004, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (120, 12005, 'Santa Cruz');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (120, 12006, 'San Antonio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20101, 'Alajuela');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20102, 'San José');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20103, 'Carrizal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20104, 'San Antonio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20105, 'Guácima');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20106, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20107, 'Sabanilla');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20108, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20109, 'Río Segundo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20110, 'Desamparados');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20111, 'Turrucares');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20112, 'Tambor');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20113, 'Garita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (201, 20114, 'Sarapiquí');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20201, 'San Ramón');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20202, 'Santiago');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20203, 'San Juan');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20204, 'Piedades Norte');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20205, 'Piedades Sur');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20206, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20207, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20208, 'Ángeles');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20209, 'Alfaro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20210, 'Volio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20211, 'Concepción');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20212, 'Zapotal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20213, 'Peñas Blancas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (202, 20214, 'San Lorenzo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (203, 20301, 'Grecia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (203, 20302, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (203, 20303, 'San José');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (203, 20304, 'San Roque');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (203, 20305, 'Tacares');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (203, 20307, 'Puente de Piedra');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (203, 20308, 'Bolivar');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (204, 20401, 'San Mateo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (204, 20402, 'Desmonte');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (204, 20403, 'Jesús María');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (204, 20404, 'Labrador');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (205, 20501, 'Atenas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (205, 20502, 'Jesús');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (205, 20503, 'Mercedes');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (205, 20504, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (205, 20505, 'Concepción');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (205, 20506, 'San José');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (205, 20507, 'Santa Eulalia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (205, 20508, 'Escobal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (206, 20601, 'Naranjo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (206, 20602, 'San Miguel');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (206, 20603, 'San José');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (206, 20604, 'Cirrí Sur');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (206, 20605, 'San Jerónimo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (206, 20606, 'San Juan');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (206, 20607, 'El Rosario');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (206, 20608, 'Palmitos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (207, 20701, 'Palmares');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (207, 20702, 'Zaragoza');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (207, 20703, 'Buenos Aires');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (207, 20704, 'Santiago');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (207, 20705, 'Candelaria');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (207, 20706, 'Esquipulas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (207, 20707, 'La Granja');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (208, 20801, 'San Pedro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (208, 20802, 'San Juan');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (208, 20803, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (208, 20804, 'Carrillos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (208, 20805, 'Sabana Redonda');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (209, 20901, 'Orotina');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (209, 20902, 'El Mastate');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (209, 20903, 'Hacienda Vieja');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (209, 20904, 'Coyolar');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (209, 20905, 'La Ceiba');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21001, 'Quesada');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21002, 'Florencia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21003, 'Buenavista');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21004, 'Aguas Zarcas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21005, 'Venecia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21006, 'Pital');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21007, 'La Fortuna');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21008, 'La Tigra');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21009, 'La Palmera');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21010, 'Venado');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21011, 'Cutris');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21012, 'Monterrey');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (210, 21013, 'Pocosol');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (211, 21101, 'Zarcero');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (211, 21102, 'Laguna');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (211, 21103, 'Tapesco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (211, 21104, 'Guadalupe');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (211, 21105, 'Palmira');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (211, 21106, 'Zapote');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (211, 21107, 'Brisas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (212, 21201, 'Sarchí Norte');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (212, 21202, 'Sarchí Sur');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (212, 21203, 'Toro Amarillo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (212, 21204, 'San Pedro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (212, 21205, 'Rodríguez');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (213, 21301, 'Upala');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (213, 21302, 'Aguas Claras');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (213, 21303, 'San José O Pizote');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (213, 21304, 'Bijagua');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (213, 21305, 'Delicias');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (213, 21306, 'Dos Ríos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (213, 21307, 'Yolillal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (213, 21308, 'Canalete');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (214, 21401, 'Los Chiles');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (214, 21402, 'Caño Negro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (214, 21403, 'El Amparo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (214, 21404, 'San Jorge');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (215, 21501, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (215, 21502, 'Buenavista');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (215, 21503, 'Cote');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (215, 21504, 'Katira');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (216, 21601, 'Río Cuarto');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (216, 21602, 'Santa Rita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (216, 21603, 'Santa Isabel');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30101, 'Oriental');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30102, 'Occidental');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30103, 'Carmen');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30104, 'San Nicolás');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30105, 'Aguacaliente o San Francisco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30106, 'Guadalupe o Arenilla');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30107, 'Corralillo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30108, 'Tierra Blanca');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30109, 'Dulce Nombre');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30110, 'Llano Grande');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (301, 30111, 'Quebradilla');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (302, 30201, 'Paraíso');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (302, 30202, 'Santiago');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (302, 30203, 'Orosi');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (302, 30204, 'Cachí');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (302, 30205, 'Llanos de Santa Lucía');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (302, 30206, 'Birrisito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (303, 30301, 'Tres Ríos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (303, 30302, 'San Diego');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (303, 30303, 'San Juan');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (303, 30304, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (303, 30305, 'Concepción');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (303, 30306, 'Dulce Nombre');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (303, 30307, 'San Ramón');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (303, 30308, 'Río Azul');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (304, 30401, 'Juan Viñas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (304, 30402, 'Tucurrique');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (304, 30403, 'Pejibaye');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30501, 'Turrialba');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30502, 'La Suiza');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30503, 'Peralta');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30504, 'Santa Cruz');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30505, 'Santa Teresita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30506, 'Pavones');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30507, 'Tuis');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30508, 'Tayutic');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30509, 'Santa Rosa');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30510, 'Tres Equis');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30511, 'La Isabel');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (305, 30512, 'Chirripó');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (306, 30601, 'Pacayas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (306, 30602, 'Cervantes');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (306, 30603, 'Capellades');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (307, 30701, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (307, 30702, 'Cot');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (307, 30703, 'Potrero Cerrado');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (307, 30704, 'Cipreses');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (307, 30705, 'Santa Rosa');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (308, 30801, 'El Tejar');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (308, 30802, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (308, 30803, 'Tobosi');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (308, 30804, 'Patio de Agua');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (401, 40101, 'Heredia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (401, 40102, 'Mercedes');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (401, 40103, 'San Francisco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (401, 40104, 'Ulloa');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (401, 40105, 'Varablanca');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (402, 40201, 'Barva');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (402, 40202, 'San Pedro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (402, 40203, 'San Pablo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (402, 40204, 'San Roque');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (402, 40205, 'Santa Lucía');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (402, 40206, 'San José de la Montaña');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (403, 40301, 'Santo Domingo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (403, 40302, 'San Vicente');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (403, 40303, 'San Miguel');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (403, 40304, 'Paracito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (403, 40305, 'Santo Tomás');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (403, 40306, 'Santa Rosa');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (403, 40307, 'Tures');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (403, 40308, 'Pará');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (404, 40401, 'Santa Bárbara');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (404, 40402, 'San Pedro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (404, 40403, 'San Juan');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (404, 40404, 'Jesús');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (404, 40405, 'Santo Domingo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (404, 40406, 'Purabá');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (405, 40501, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (405, 40502, 'San Josecito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (405, 40503, 'Santiago');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (405, 40504, 'Ángeles');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (405, 40505, 'Concepción');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (406, 40601, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (406, 40602, 'San José');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (406, 40603, 'Concepción');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (406, 40604, 'San Francisco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (407, 40701, 'San Antonio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (407, 40702, 'La Ribera');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (407, 40703, 'La Asunción');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (408, 40801, 'San Joaquín');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (408, 40802, 'Barrantes');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (408, 40803, 'Llorente');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (409, 40901, 'San Pablo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (409, 40902, 'Rincón de Sabanilla');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (410, 41001, 'Puerto Viejo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (410, 41002, 'La Virgen');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (410, 41003, 'Las Horquetas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (410, 41004, 'Llanuras del Gaspar');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (410, 41005, 'Cureña');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (501, 50101, 'Liberia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (501, 50102, 'Cañas Dulces');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (501, 50103, 'Mayorga');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (501, 50104, 'Nacascolo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (501, 50105, 'Curubandé');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (502, 50201, 'Nicoya');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (502, 50202, 'Mansión');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (502, 50203, 'San Antonio');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (502, 50204, 'Quebrada Honda');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (502, 50205, 'Sámara');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (502, 50206, 'Nosara');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (502, 50207, 'Belén de Nosarita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50301, 'Santa Cruz');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50302, 'Bolsón');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50303, 'Veintisiete de Abril');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50304, 'Tempate');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50305, 'Cartagena');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50306, 'Cuajiniquil');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50307, 'Diriá');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50308, 'Cabo Velas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (503, 50309, 'Tamarindo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (504, 50401, 'Bagaces');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (504, 50402, 'La Fortuna');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (504, 50403, 'Mogote');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (504, 50404, 'Río Naranjo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (505, 50501, 'Filadelfia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (505, 50502, 'Palmira');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (505, 50503, 'Sardinal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (505, 50504, 'Belén');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (506, 50601, 'Cañas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (506, 50602, 'Palmira');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (506, 50603, 'San Miguel');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (506, 50604, 'Bebedero');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (506, 50605, 'Porozal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (507, 50701, 'Las Juntas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (507, 50702, 'Sierra');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (507, 50703, 'San Juan');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (507, 50704, 'Colorado');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (508, 50801, 'Tilarán');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (508, 50802, 'Quebrada Grande');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (508, 50803, 'Tronadora');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (508, 50804, 'Santa Rosa');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (508, 50805, 'Líbano');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (508, 50806, 'Tierras Morenas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (508, 50807, 'Arenal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (508, 50808, 'Cabeceras');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (509, 50901, 'Carmona');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (509, 50902, 'Santa Rita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (509, 50903, 'Zapotal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (509, 50904, 'San Pablo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (509, 50905, 'Porvenir');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (509, 50906, 'Bejuco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (510, 51001, 'La Cruz');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (510, 51002, 'Santa Cecilia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (510, 51003, 'La Garita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (510, 51004, 'Santa Elena');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (511, 51101, 'Hojancha');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (511, 51102, 'Monte Romo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (511, 51103, 'Puerto Carrillo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (511, 51104, 'Huacas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (511, 51105, 'Matambú');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60101, 'Puntarenas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60102, 'Pitahaya');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60103, 'Chomes');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60104, 'Lepanto');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60105, 'Paquera');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60106, 'Manzanillo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60107, 'Guacimal');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60108, 'Barranca');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60110, 'Isla del Coco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60111, 'Cóbano');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60112, 'Chacarita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60113, 'Chira');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60114, 'Acapulco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60115, 'El Roble');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (601, 60116, 'Arancibia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (602, 60201, 'Espíritu Santo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (602, 60202, 'San Juan Grande');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (602, 60203, 'Macacona');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (602, 60204, 'San Rafael');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (602, 60205, 'San Jerónimo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (602, 60206, 'Caldera');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60301, 'Buenos Aires');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60302, 'Volcán');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60303, 'Potrero Grande');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60304, 'Boruca');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60305, 'Pilas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60306, 'Colinas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60307, 'Chánguena');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60308, 'Biolley');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (603, 60309, 'Brunka');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (604, 60401, 'Miramar');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (604, 60402, 'La Unión');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (604, 60403, 'San Isidro');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (605, 60501, 'Puerto Cortés');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (605, 60502, 'Palmar');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (605, 60503, 'Sierpe');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (605, 60504, 'Bahía Ballena');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (605, 60505, 'Piedras Blancas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (605, 60506, 'Bahía Drake');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (606, 60601, 'Quepos');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (606, 60602, 'Savegre');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (606, 60603, 'Naranjito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (607, 60701, 'Golfito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (607, 60702, 'Puerto Jiménez');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (607, 60703, 'Guaycará');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (607, 60704, 'Pavón');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (608, 60801, 'San Vito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (608, 60802, 'Sabalito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (608, 60803, 'Aguabuena');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (608, 60804, 'Limoncito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (608, 60805, 'Pittier');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (608, 60806, 'Gutiérrez Braun');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (609, 60901, 'Parrita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (610, 61001, 'Corredor');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (610, 61002, 'La Cuesta');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (610, 61003, 'Canoas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (610, 61004, 'Laurel');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (611, 61101, 'Jacó');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (611, 61102, 'Tárcoles');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (611, 61103, 'Lagunillas');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (612, 61201, 'Monteverde');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (701, 70101, 'Limón');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (701, 70102, 'Valle La Estrella');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (701, 70103, 'Río Blanco');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (701, 70104, 'Matama');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (702, 70201, 'Guápiles');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (702, 70202, 'Jiménez');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (702, 70203, 'Rita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (702, 70204, 'Roxana');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (702, 70205, 'Cariari');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (702, 70206, 'Colorado');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (702, 70207, 'La Colonia');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (703, 70301, 'Siquirres');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (703, 70302, 'Pacuarito');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (703, 70303, 'Florida');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (703, 70304, 'Germania');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (703, 70305, 'El Cairo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (703, 70306, 'Alegría');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (703, 70307, 'Reventazón');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (704, 70401, 'Bratsi');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (704, 70402, 'Sixaola');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (704, 70403, 'Cahuita');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (704, 70404, 'Telire');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (705, 70501, 'Matina');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (705, 70502, 'Batán');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (705, 70503, 'Carrandí');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (706, 70601, 'Guácimo');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (706, 70602, 'Mercedes');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (706, 70603, 'Pocora');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (706, 70604, 'Río Jiménez');

INSERT INTO TBL_DISTRITO (ID_CANTON, ID_DISTRITO, NOMBRE_DISTRITO) 
VALUES (706, 70605, 'Duacarí');

-- Llamando a la función
SELECT pkg_distrito.consultar_distrito_con_id(10101) AS resultado FROM DUAL;
SELECT pkg_distrito.consultar_distrito_con_id(10105) AS resultado FROM DUAL;


--Llamando las vistas Distrito
Select "NUMERO DE DISTRITOS" from VISTA_CANTIDAD_DE_DISTRITOS;
Select "NOMBRE DEL DISTRITO", "NUMERO DE CANTON", "NOMBRE DEL CANTON", "PERTENECE A LA PROVINCIA DE" from VISTA_LISTAR_DISTRITO_Y_PROVINCIA;
Select "NOMBRE DEL DISTRITO", "NOMBRE DEL CANTON" from VISTA_LISTAR_DISTRITO;
