-- TABLA DE EMPLEADOS
CREATE TABLE TBL_EMPLEADO(
    ID_EMPLEADO NUMBER NOT NULL PRIMARY KEY,
    IDENTIFICACION NUMBER NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    SALARIO NUMBER(10,2) NOT NULL,
    ID_CLIENTE NUMBER,
    HORARIO DATE,
    CONSTRAINT FK_EMPLEADO_CLIENTE 
    FOREIGN KEY (ID_CLIENTE) 
    REFERENCES TBL_CLIENTE (ID_CLIENTE)
);

-- CRUD PARA LA TABLA DE EMPLEADOS
-- PROCEDIMIENTO PARA REGISTRAR EMPLEADOS
CREATE OR REPLACE PROCEDURE SP_INSERTAR_EMPLEADO(
    P_ID_EMPLEADO TBL_EMPLEADO.ID_EMPLEADO%TYPE,
    P_IDENTIFICACION TBL_EMPLEADO.IDENTIFICACION%TYPE,
    P_NOMBRE TBL_EMPLEADO.NOMBRE%TYPE,
    P_APELLIDO TBL_EMPLEADO.APELLIDO%TYPE,
    P_SALARIO TBL_EMPLEADO.SALARIO%TYPE,
    P_ID_CLIENTE TBL_EMPLEADO.ID_CLIENTE%TYPE,
    P_HORARIO TBL_EMPLEADO.HORARIO%TYPE
)AS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM TBL_EMPLEADO
    WHERE ID_EMPLEADO = P_ID_EMPLEADO;

    IF V_COUNT > 0 THEN

        DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REGISTRO CON EL ID ' || P_ID_EMPLEADO);

    ELSE
        INSERT INTO TBL_EMPLEADO(ID_EMPLEADO,IDENTIFICACION,NOMBRE,APELLIDO,SALARIO,ID_CLIENTE,HORARIO)
        VALUES (P_ID_EMPLEADO,P_IDENTIFICACION,P_NOMBRE,P_APELLIDO,P_SALARIO,P_ID_CLIENTE,P_HORARIO);
        COMMIT;
    
        DBMS_OUTPUT.PUT_LINE('REGISTRO REALIZADO');

    END IF;
END;

-- PROCEDIMIENTO PARA LEER DATOS DE UN EMPLEADO
CREATE OR REPLACE PROCEDURE SP_LEER_EMPLEADO(
    P_ID_EMPLEADO NUMBER
)IS
    V_IDENTIFICACION TBL_EMPLEADO.IDENTIFICACION%TYPE;
    V_NOMBRE TBL_EMPLEADO.NOMBRE%TYPE;
    V_APELLIDO TBL_EMPLEADO.APELLIDO%TYPE;
    V_SALARIO TBL_EMPLEADO.SALARIO%TYPE;
    V_ID_CLIENTE TBL_EMPLEADO.ID_CLIENTE%TYPE;
    V_HORARIO TBL_EMPLEADO.HORARIO%TYPE;
BEGIN    
    SELECT IDENTIFICACION, NOMBRE, APELLIDO, SALARIO, ID_CLIENTE, HORARIO INTO V_IDENTIFICACION, V_NOMBRE, V_APELLIDO, V_SALARIO, V_ID_CLIENTE, V_HORARIO
    FROM TBL_EMPLEADO
    WHERE ID_EMPLEADO = P_ID_EMPLEADO;
    
    DBMS_OUTPUT.PUT_LINE('IDENTIFICACION: ' || V_IDENTIFICACION || ', NOMBRE: ' || V_NOMBRE || ', APELLIDO: ' || V_APELLIDO || ', SALARIO: ' || V_SALARIO || ', ID_CLIENTE: ' || V_ID_CLIENTE || ', HORARIO: ' || V_HORARIO);
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('EL EMPLEADO CON EL ID ' || P_ID_EMPLEADO || ' NO FUE ENCONTRADO.');
END;

-- PROCEDIMIENTO PARA ACTUALIZAR UN EMPLEADO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_EMPLEADO(
    P_ID_EMPLEADO TBL_EMPLEADO.ID_EMPLEADO%TYPE,
    P_IDENTIFICACION TBL_EMPLEADO.IDENTIFICACION%TYPE,
    P_NOMBRE TBL_EMPLEADO.NOMBRE%TYPE,
    P_APELLIDO TBL_EMPLEADO.APELLIDO%TYPE,
    P_SALARIO TBL_EMPLEADO.SALARIO%TYPE,
    P_ID_CLIENTE TBL_EMPLEADO.ID_CLIENTE%TYPE,
    P_HORARIO TBL_EMPLEADO.HORARIO%TYPE
)AS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM TBL_EMPLEADO
    WHERE ID_EMPLEADO = P_ID_EMPLEADO;

    IF V_COUNT > 0 THEN

        UPDATE TBL_EMPLEADO
        SET IDENTIFICACION = P_IDENTIFICACION, NOMBRE = P_NOMBRE, APELLIDO = P_APELLIDO, SALARIO = P_SALARIO, ID_CLIENTE = P_ID_CLIENTE, HORARIO = P_HORARIO
        WHERE ID_EMPLEADO = P_ID_EMPLEADO;
        COMMIT;

        DBMS_OUTPUT.PUT_LINE('EL EMPLEADO CON EL ID ' || P_ID_EMPLEADO || ' HA SIDO ACTUALIZADO.');

    ELSE 

        DBMS_OUTPUT.PUT_LINE('EL EMPLEADO CON EL ID ' || P_ID_EMPLEADO || ' NO FUE ENCONTRADO.');

    END IF;
END;

-- PRECEDIMIENTO PARA ELIMINAR UN EMPLEADO
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_EMPLEADO(
    P_ID_EMPLEADO TBL_EMPLEADO.ID_EMPLEADO%TYPE
)AS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM TBL_EMPLEADO
    WHERE ID_EMPLEADO = P_ID_EMPLEADO;

    IF V_COUNT > 0 THEN

        DELETE FROM TBL_EMPLEADO
        WHERE ID_EMPLEADO = P_ID_EMPLEADO;
        COMMIT;

        DBMS_OUTPUT.PUT_LINE('EL EMPLEADO CON EL ID ' || P_ID_EMPLEADO || ' FUE ELIMINADO CORRECTAMENTE.');

    ELSE

        DBMS_OUTPUT.PUT_LINE('EL EMPLEADO CON EL ID ' || P_ID_EMPLEADO || ' NO FUE ENCONTRADO.');

    END IF;
END;